# CI/CD Watch Mode - Automatyczne buildowanie i commitowanie przy zmianach
# Wersja: 1.0
# Data: 2024-12-12

param(
    [int]$IntervalSeconds = 30,
    [string]$Configuration = "Release",
    [switch]$AutoCommit = $false,
    [switch]$AutoPush = $false,
    [string[]]$WatchPaths = @("*.cs", "*.csproj", "*.json"),
    [string[]]$ExcludePaths = @("bin", "obj", "node_modules")
)

Write-Host "=== CI/CD Watch Mode ===" -ForegroundColor Green
Write-Host "Interval: $IntervalSeconds seconds" -ForegroundColor Cyan
Write-Host "Configuration: $Configuration" -ForegroundColor Cyan
Write-Host "Auto Commit: $AutoCommit" -ForegroundColor Cyan
Write-Host "Auto Push: $AutoPush" -ForegroundColor Cyan
Write-Host ""
Write-Host "Press Ctrl+C to stop..." -ForegroundColor Yellow
Write-Host ""

# Funkcja do sprawdzania zmian
function Get-FileChanges {
    $changes = git status --porcelain | Where-Object {
        $file = $_ -replace '^.. ', ''
        $excluded = $false
        foreach ($exclude in $ExcludePaths) {
            if ($file -like "*$exclude*") {
                $excluded = $true
                break
            }
        }
        -not $excluded
    }
    return $changes
}

# Funkcja do buildu
function Invoke-Build {
    Write-Host "[$(Get-Date -Format 'HH:mm:ss')] Building..." -ForegroundColor Yellow
    
    $output = dotnet build --configuration $Configuration --verbosity quiet 2>&1
    
    if ($LASTEXITCODE -eq 0) {
        Write-Host "[$(Get-Date -Format 'HH:mm:ss')] ? Build successful" -ForegroundColor Green
        return $true
    } else {
        Write-Host "[$(Get-Date -Format 'HH:mm:ss')] ? Build failed" -ForegroundColor Red
        Write-Host $output -ForegroundColor Red
        return $false
    }
}

# Funkcja do commitowania
function Invoke-AutoCommit {
    $changes = Get-FileChanges
    
    if (-not $changes) {
        Write-Host "[$(Get-Date -Format 'HH:mm:ss')] No changes to commit" -ForegroundColor Gray
        return $false
    }
    
    Write-Host "[$(Get-Date -Format 'HH:mm:ss')] Committing changes..." -ForegroundColor Yellow
    
    # Dodaj zmiany
    git add .
    
    # Utwórz commit message
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $changedFiles = ($changes | Measure-Object).Count
    $commitMessage = "Auto-commit: Build successful at $timestamp`n`nChanged files: $changedFiles`n[Auto-generated by CI/CD watch mode]"
    
    git commit -m $commitMessage
    
    if ($LASTEXITCODE -eq 0) {
        $commitHash = git rev-parse --short HEAD
        Write-Host "[$(Get-Date -Format 'HH:mm:ss')] ? Committed: $commitHash" -ForegroundColor Green
        return $true
    } else {
        Write-Host "[$(Get-Date -Format 'HH:mm:ss')] ? Commit failed" -ForegroundColor Red
        return $false
    }
}

# Funkcja do pushowania
function Invoke-AutoPush {
    Write-Host "[$(Get-Date -Format 'HH:mm:ss')] Pushing to remotes..." -ForegroundColor Yellow
    
    $currentBranch = git rev-parse --abbrev-ref HEAD
    $remotes = @("prospeo", "origin")
    
    foreach ($remote in $remotes) {
        git push $remote $currentBranch 2>&1 | Out-Null
        if ($LASTEXITCODE -eq 0) {
            Write-Host "[$(Get-Date -Format 'HH:mm:ss')] ? Pushed to $remote" -ForegroundColor Green
        } else {
            Write-Host "[$(Get-Date -Format 'HH:mm:ss')] ? Failed to push to $remote" -ForegroundColor Yellow
        }
    }
}

# Zapisz pocz¹tkowy stan
$lastBuildTime = Get-Date
$lastCommitHash = git rev-parse HEAD

# G³ówna pêtla
$iteration = 0
while ($true) {
    $iteration++
    
    try {
        # SprawdŸ czy s¹ zmiany
        $changes = Get-FileChanges
        
        if ($changes) {
            Write-Host ""
            Write-Host "=== Iteration $iteration ===" -ForegroundColor Cyan
            Write-Host "[$(Get-Date -Format 'HH:mm:ss')] Changes detected:" -ForegroundColor Yellow
            $changes | ForEach-Object { Write-Host "  $_" -ForegroundColor Gray }
            
            # Uruchom build
            $buildSuccess = Invoke-Build
            
            if ($buildSuccess) {
                $lastBuildTime = Get-Date
                
                # Auto commit jeœli w³¹czone
                if ($AutoCommit) {
                    $commitSuccess = Invoke-AutoCommit
                    
                    # Auto push jeœli w³¹czone i commit siê powiód³
                    if ($AutoPush -and $commitSuccess) {
                        Invoke-AutoPush
                    }
                }
            } else {
                Write-Host "[$(Get-Date -Format 'HH:mm:ss')] Skipping commit due to build failure" -ForegroundColor Yellow
            }
        } else {
            # Wyœwietl status co 5 iteracji
            if ($iteration % 5 -eq 0) {
                $timeSinceLastBuild = (Get-Date) - $lastBuildTime
                Write-Host "[$(Get-Date -Format 'HH:mm:ss')] Watching... (last build: $($timeSinceLastBuild.TotalMinutes.ToString('F1')) min ago)" -ForegroundColor DarkGray
            }
        }
        
        # Czekaj przed nastêpn¹ iteracj¹
        Start-Sleep -Seconds $IntervalSeconds
        
    } catch {
        Write-Host "[$(Get-Date -Format 'HH:mm:ss')] ? Error: $($_.Exception.Message)" -ForegroundColor Red
        Start-Sleep -Seconds $IntervalSeconds
    }
}
